version: '3.8'
services:
  caddy:
    image: caddy:2
    container_name: caddy-tailscale
    restart: unless-stopped
    ports:
      - "80:80"
      - "8443:8443"
      - "2019:2019"
    volumes:
      - ./docker-configs/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - /home/keith/chat-copilot/webapp/public:/srv:ro
      - /etc/ssl/certs/ubuntuaicodeserver.tail5137b4.ts.net.crt:/etc/ssl/certs/ubuntuaicodeserver.tail5137b4.ts.net.crt:ro
      - /etc/ssl/private/ubuntuaicodeserver.tail5137b4.ts.net.key:/etc/ssl/private/ubuntuaicodeserver.tail5137b4.ts.net.key:ro
    networks:
      - ai-platform

  magentic-one:
    build: ./python/services
    container_name: magentic-one
    restart: unless-stopped
    ports:
      - "11003:11003"
    networks:
      - ai-platform

volumes:
  caddy_data:
  caddy_config:

networks:
  ai-platform:
    driver: bridge
