[project]
name = "chat-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autogenstudio[ui]>=0.4.2.2",
    "flask>=3.1.1",
    "pyautogen>=0.9",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
]
