# Azure DevOps Pipeline for Diff Test Suite Agent
trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: qodo-credentials

stages:
- stage: TestGeneration
  displayName: 'Test Generation'
  jobs:
  - job: GenerateTests
    displayName: 'Generate Tests'
    steps:
    - task: Docker@2
      displayName: 'Run Diff Test Suite Agent'
      inputs:
        command: 'run'
        image: 'qodo/qodo-gen-cli:latest'
        arguments: >
          --prompt diff-test-suite
          --agent-file path/to/agent.toml
          --key-value-pairs "base_branch=$(System.PullRequest.TargetBranch),files_to_ignore=package-lock.json,*.md,run_tests=true"
        envVars: |
          QODO_API_KEY=$(qodo-api-key)
          AZURE_TOKEN=$(System.AccessToken)