services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-tailscale
    restart: unless-stopped
    # No port bindings when using host networking - Caddy binds directly to host ports
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:ro
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    network_mode: host
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:2019/config/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:
