
version: '3.8'

services:
  nginx-proxy-manager:
    volumes:
      - /opt/tailscale-certs:/etc/ssl/tailscale:ro
      - ./nginx-configs:/etc/nginx/conf.d:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
