# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3

repos:
  # Qodo diff review hook - runs first to catch issues early
  - repo: local
    hooks:
      - id: qodo-diff-review
        name: Qodo Diff Review
        entry: |
          bash -c "
            echo 'Starting Qodo Merge auto diff review...' > diff_review_post_commit.md          
            echo 'Starting Qodo Merge auto diff review...' >&2
            qodo --ci diff_review_post_commit > diff_review_post_commit_log.txt 2>&1 &
          "
        language: system
        stages: [post-commit]
        pass_filenames: false
        always_run: true
        verbose: true
        description: "Run qodo diff_review on latest committed changes"