# Version of the agent configuration standard
version = "1.0"



 [commands.diff_review_post_commit]
 description = "Review the latest commit and provide code suggestions via Qodo Merge"
 instructions = """
 1) Get the git diff of all the commits that are in the current local branch, but are not present in the main branch
 2) Use Qodo Merge 'improve' tool for generating the code suggestions from this latest git diff.
 3) Take the exact output from the Qodo Merge 'improve' tool as a string
 4) write this exact string to a local file named 'diff_review_post_commit.md' in the current directory.
 """
execution_strategy = "act"
available_tools = ["git", "filesystem", "qodo_merge"]
