version: '3.8'

# Docker Compose Override for Missing Services
# This file provides alternatives for services that fail to build

services:
  # Alternative Webhook Server (using simple Node.js image)
  webhook-server-simple:
    image: node:18-alpine
    container_name: ai-platform-webhook-simple
    restart: unless-stopped
    ports:
      - "11002:11002"
    environment:
      - NODE_ENV=production
      - WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET:-default-secret}
      - WEBHOOK_PORT=11002
    command: >
      sh -c "
        echo 'Starting simple webhook server...' &&
        mkdir -p /app &&
        cd /app &&
        echo 'const express = require(\"express\"); const app = express(); app.get(\"/health\", (req, res) => res.json({status: \"ok\"})); app.listen(11002, () => console.log(\"Webhook server running on port 11002\"));' > server.js &&
        npm init -y &&
        npm install express &&
        node server.js
      "
    networks:
      - ai-platform
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:11002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Alternative VS Code Server (using official code-server image)
  vscode-server-simple:
    image: codercom/code-server:latest
    container_name: ai-platform-vscode-simple
    restart: unless-stopped
    ports:
      - "57081:8080"
    environment:
      - PASSWORD=${VSCODE_PASSWORD:-vscode123}
      - SUDO_PASSWORD=${VSCODE_PASSWORD:-vscode123}
    volumes:
      - /home/keith/chat-copilot:/home/coder/workspace
    networks:
      - ai-platform
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ai-platform:
    external: true
