version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-simple
    ports:
      - "80:80"
    volumes:
      - ./nginx-simple.conf:/etc/nginx/conf.d/default.conf
      - ./webapp/public:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - chat-copilot-backend
      - chat-copilot-frontend

  chat-copilot-backend:
    build:
      context: ./webapi
    container_name: chat-copilot-backend
    ports:
      - "11000:11000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:11000
    restart: unless-stopped

  chat-copilot-frontend:
    build:
      context: ./webapp
    container_name: chat-copilot-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URI=http://100.123.10.72:11000/
    restart: unless-stopped
    depends_on:
      - chat-copilot-backend