# GitLab CI Configuration for Code Review Agent
stages:
  - review

code_review:
  stage: review
  image: qodo/qodo-gen-cli:latest
  script:
    - |
      qodo-gen-cli \
        --prompt code-review \
        --agent-file path/to/agent.toml \
        --key-value-pairs "target_branch=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-main},severity_threshold=medium,focus_areas=security,performance,include_suggestions=true"
  variables:
    QODO_API_KEY: $QODO_API_KEY
    GITLAB_TOKEN: $CI_JOB_TOKEN
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"